---
# tasks file for collectd

- name: Install collectd
  apt: pkg={{ item }}
  with_items:
    - collectd
    - collectd-utils

- name: config file /etc/collectd/collectd.conf
  blockinfile:
    path: /etc/collectd/collectd.conf
    block: |
      Hostname "graph_host"
      LoadPlugin write_graphite
      <Plugin write_graphite>
         <Node "graphing">
             Host "192.168.20.14"
             Port "2003"
             Protocol "tcp"
             LogSendErrors true
             Prefix "collectd."
             StoreRates true
             AlwaysAppendDS false
             EscapeCharacter "_"
         </Node>
      </Plugin>
  notify:
   - restart collectd
